stages:
  - build
  - deploy

variables:
  IMAGE_JS: js
  CONTAINER_RELEASE_JS: docker-registry.beta.innovation.insee.eu/alpha/sic/divers/pearl-poc/js:latest

package-js-prod:
  stage: build
  tags:
    - maven
  script:
    - "yarn config set cache-folder /mnt/mesos/sandbox/yarnrepo"
    - "yarn install"
    - "yarn run build"
    - "docker build -t $CONTAINER_RELEASE_JS ."
    - "docker push $CONTAINER_RELEASE_JS"
  only:
    - master@sic/divers/pearl-poc

deploy:
  stage: deploy
  only:
    - master@sic/divers/pearl-poc
  tags:
    - maven
  script:
    - "APP_ID=`cat marathon.json | jq .id -r`"
    - 'curl -d@marathon.json -H "Content-Type: application/json" -X PUT http://deploy.alpha.innovation.insee.eu/v2/apps/$APP_ID?force=true'
    - "curl -X POST http://deploy.alpha.innovation.insee.eu/v2/apps/$APP_ID/restart?force=true"
  environment:
    name: prod
    url: http://pearl-poc.dev.innovation.insee.eu
